# Generated by Django 6.0.7 on 2026-08-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_order_id', models.CharField(max_length=255)),
                ('tracking_code', models.CharField(blank=True, max_length=255)),
                ('package_type', models.CharField(blank=True, max_length=100)),
                ('lifecycle_status', models.CharField(blank=True, max_length=100)),
                ('daraz_status', models.CharField(blank=True, max_length=100)),
                ('daraz_status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('buyer_reason', models.CharField(blank=True, max_length=255)),
                ('item_value_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_full_package_return', models.BooleanField(default=True)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_packages', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_packages', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraz_item_id', models.CharField(blank=True, max_length=255)),
                ('sku_string', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('quantity_returned', models.IntegerField(default=1)),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('item_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condition_recorded', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='orders.orderitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='stores.store')),
                ('return_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnpackage')),
            ],
        ),
        migrations.AddIndex(
            model_name='returnpackage',
            index=models.Index(fields=['store', 'daraz_status_updated_at'], name='returns_ret_store_i_d8f737_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnpackage',
            constraint=models.UniqueConstraint(fields=('store', 'return_order_id'), name='unique_store_return_pkg'),
        ),
    ]
