# Generated by Django 6.0.7 on 2026-08-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackageInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('recorded_by', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('photos', models.JSONField(default=list)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='returns.returnitem')),
                ('return_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='returns.returnpackage')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(max_length=100)),
                ('condition_recorded', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('is_late_filing', models.BooleanField(default=False)),
                ('expected_refund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daraz_claim_ref', models.CharField(blank=True, max_length=255)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_source_field', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='returns.returnpackage')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='returns.returnclaim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='claims/evidence/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('exif_stripped', models.BooleanField(default=False)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='returns.returnclaim')),
            ],
        ),
    ]
