[pytest]
DJANGO_SETTINGS_MODULE = config.settings.local
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --reuse-db
env =
    FIELD_ENCRYPTION_KEY=N0L2Fh3GZtT7mJbXk2O4u1N6V-A3R8zYc9kQ7aBwR6k=
