# Generated by Django 6.0.7 on 2026-08-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=255)),
                ('tracking_code', models.CharField(blank=True, max_length=255)),
                ('shipment_provider', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('label_url_cached', models.URLField(blank=True, max_length=1000)),
                ('label_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_identifier', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('address_line', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraz_order_id', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('raw_status_list', models.JSONField(default=list)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('is_cod', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voucher', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voucher_platform', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voucher_seller', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_count', models.IntegerField(default=0)),
                ('created_at_daraz', models.DateTimeField(blank=True, null=True)),
                ('updated_at_daraz', models.DateTimeField(blank=True, null=True)),
                ('promised_shipping_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_info', models.CharField(blank=True, max_length=500)),
                ('remarks', models.TextField(blank=True)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraz_order_item_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('sku_string', models.CharField(max_length=255)),
                ('shop_sku', models.CharField(blank=True, max_length=255)),
                ('variation', models.CharField(blank=True, max_length=500)),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voucher_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voucher_code', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('shipment_provider', models.CharField(blank=True, max_length=255)),
                ('tracking_code', models.CharField(blank=True, max_length=255)),
                ('package_id', models.CharField(blank=True, max_length=255)),
                ('shipping_type', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reason_detail', models.TextField(blank=True)),
                ('is_digital', models.BooleanField(default=False)),
                ('promised_shipping_time', models.DateTimeField(blank=True, null=True)),
                ('created_at_daraz', models.DateTimeField(blank=True, null=True)),
                ('updated_at_daraz', models.DateTimeField(blank=True, null=True)),
                ('sla_time_stamp', models.DateTimeField(blank=True, null=True)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
