# Generated by Django 6.0.7 on 2026-08-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.sku'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='stores.store'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='stores.store'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('store', 'hashed_identifier'), name='unique_store_customer'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status', 'created_at_daraz'], name='orders_orde_store_i_6dac89_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'created_at_daraz'], name='orders_orde_store_i_27baa0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'updated_at_daraz'], name='orders_orde_store_i_0b2ea2_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('store', 'daraz_order_id'), name='unique_store_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['store', 'status'], name='orders_orde_store_i_41ba69_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['store', 'tracking_code'], name='orders_orde_store_i_82273b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['store', 'package_id'], name='orders_orde_store_i_2e43d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('store', 'daraz_order_item_id'), name='unique_store_order_item'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('store', 'package_id'), name='unique_store_package'),
        ),
    ]
