# Generated by Django 6.0.7 on 2026-08-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=100)),
                ('fee_name', models.CharField(max_length=255)),
                ('statement_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('vat_in_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('paid_status', models.CharField(blank=True, max_length=100)),
                ('payment_ref_id', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(max_length=255)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_status', models.CharField(blank=True, max_length=100)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_statements', to='stores.store')),
            ],
        ),
    ]
