# Generated by Django 6.0.7 on 2026-08-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='financestatement',
            index=models.Index(fields=['store', '-period_end'], name='finance_fin_store_i_efe702_idx'),
        ),
        migrations.AddConstraint(
            model_name='financestatement',
            constraint=models.UniqueConstraint(fields=('store', 'statement_number'), name='unique_store_statement'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['store', 'transaction_date'], name='finance_fin_store_i_7f9215_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['store', 'order'], name='finance_fin_store_i_584b53_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransaction',
            index=models.Index(fields=['store', 'transaction_type'], name='finance_fin_store_i_e372a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='financetransaction',
            constraint=models.UniqueConstraint(fields=('store', 'transaction_number'), name='unique_store_transaction'),
        ),
    ]
