# Generated by Django 6.0.7 on 2026-08-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('orders', '0003_orderitem_profit_amount_orderitem_profit_computed_at_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='queued', max_length=50)),
                ('orders_examined', models.IntegerField(default=0)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expected_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('issues_count', models.IntegerField(default=0)),
                ('report', models.JSONField(default=dict)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='audits/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_audits', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount_impact', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('evidence', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_note', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='finance.financeaudit')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_issues', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_issues', to='orders.orderitem')),
            ],
        ),
    ]
