# Generated by Django 6.0.7 on 2026-08-03 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_orderitem_profit_amount_orderitem_profit_computed_at_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ids', models.JSONField(default=list)),
                ('status', models.CharField(default='queued', max_length=50)),
                ('output_kind', models.CharField(default='merged_pdf', max_length=50)),
                ('progress_pct', models.IntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='label_outputs/')),
                ('page_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_jobs', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='LabelJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error', models.TextField(blank=True)),
                ('page_index', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labels.labeljob')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('page_size', models.CharField(default='4x6in', max_length=50)),
                ('width_mm', models.FloatField(default=101.6)),
                ('height_mm', models.FloatField(default=152.4)),
                ('dpi', models.IntegerField(default=300)),
                ('canvas_json', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('is_starter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='labeljob',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.labeltemplate'),
        ),
        migrations.CreateModel(
            name='LabelAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='label_assets/')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_assets', to='stores.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'checksum'), name='unique_store_label_asset')],
            },
        ),
        migrations.AddConstraint(
            model_name='labeltemplate',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_store_label_template'),
        ),
    ]
