# Generated by Django 6.0.7 on 2026-08-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraz_item_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('primary_category', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('main_image_url', models.URLField(blank=True, max_length=1000)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraz_sku_id', models.CharField(blank=True, max_length=255)),
                ('seller_sku', models.CharField(max_length=255)),
                ('shop_sku', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('variation', models.JSONField(default=dict)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('package_weight', models.CharField(blank=True, max_length=50)),
                ('package_length', models.CharField(blank=True, max_length=50)),
                ('package_width', models.CharField(blank=True, max_length=50)),
                ('package_height', models.CharField(blank=True, max_length=50)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='SkuCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV Import'), ('api', 'API')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='products.sku')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'daraz_item_id'), name='unique_store_product'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('store', 'seller_sku'), name='unique_store_sku'),
        ),
        migrations.AddIndex(
            model_name='skucost',
            index=models.Index(fields=['sku', '-effective_from'], name='products_sk_sku_id_b16eeb_idx'),
        ),
    ]
